# Generated by Django 5.2 on 2025-04-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_actaentrega_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
