# Generated by Django 5.2 on 2025-04-19 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_actaentrega_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='actaentrega',
            old_name='cerrada_por_tecnico',
            new_name='acta',
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='cerrada_por_tecnico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='tipo',
            field=models.CharField(choices=[('recuperados', 'Entrega de materiales recuperados'), ('reparados', 'Entrega de materiales reparados'), ('reparacion_diaria', 'Reparación diaria de laboratorio'), ('devolucion', 'Devolución al almacén')], default='reparacion_diaria', max_length=30, verbose_name='Tipo de acta'),
        ),
        migrations.AlterField(
            model_name='actaentrega',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
