# Generated by Django 5.2 on 2025-05-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_firmada_por_tecnico_actaentrega_acta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='tipo',
            field=models.CharField(blank=True, choices=[('recuperados', 'Entrega de materiales recuperados'), ('reparados', 'Entrega de materiales reparados'), ('reparacion_diaria', 'Reparación diaria de laboratorio'), ('devolucion', 'Devolución al almacén')], max_length=30, null=True),
        ),
    ]
